=== mplaksyuk/RO/lab7/src/main/java/manager.dtd
<!ELEMENT Manager (Team*)>
        <!ELEMENT Team (Player*)>
        <!ELEMENT Player (#PCDATA)>
        <!ATTLIST Team
                id ID #REQUIRED
                name CDATA #REQUIRED
                >
        <!ATTLIST Player
                playerId ID #REQUIRED
                teamId IDREF #REQUIRED
                name CDATA #REQUIRED
                age CDATA #REQUIRED
                >

=== mplaksyuk/RO/lab7/src/main/java/manager.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Manager SYSTEM "manager.dtd">
<Manager><Team id="team0" name="Lester"><Player age="1987" name="Mishko" playerId="id0" teamId="team0"/></Team><Team id="team3" name="Metalist"><Player age="69" name="Somebody" playerId="id3" teamId="team3"/><Player age="47" name="Dream" playerId="id4" teamId="team3"/></Team><Team id="team1" name="Liverpool"><Player age="23" name="Mane" playerId="id1" teamId="team1"/></Team><Team id="team2" name="Man city"><Player age="18" name="Aboba" playerId="id2" teamId="team2"/><Player age="19" name="Clown" playerId="id5" teamId="team2"/></Team></Manager>
